[package]
name = "admin-app"
version = "0.1.0"
authors = ["Conor Patrick <conor@solokeys.com>", "Nicolas Stalder <nicolas@solokeys.com>"]
repository = "https://github.com/solokeys/admin-app"
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "Administrative Trussed app for SoloKeys Solo 2 security keys"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apdu-dispatch = "0.1"
cbor-smol = "0.4.0"
ctaphid-dispatch = "0.1"
delog = "0.1"
iso7816 = "0.1"
littlefs2 = "0.4"
serde = { version = "1.0.180", default-features = false }
strum_macros = "0.25.2"
trussed = "0.1"

se05x = { version = "0.0.1", optional = true }
embedded-hal = { version = "0.2.7", optional = true }
hex-literal = "0.4.1"
rand_chacha = { version = "0.3.1", optional = true, default-features = false }
trussed-se050-backend = { version = "0.1.0", optional = true }

[features]
default = []
se050 = ["trussed-se050-backend"]

log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []

[patch.crates-io]
ctaphid-dispatch = { git = "https://github.com/trussed-dev/ctaphid-dispatch.git", rev = "57cb3317878a8593847595319aa03ef17c29ec5b" }
trussed-auth = { git = "https://github.com/Nitrokey/trussed-auth", rev = "49c13eae6d9a225676191d4776d514848e4eab5b" }
trussed-staging = { git = "https://github.com/Nitrokey/trussed-staging.git", rev = "83e33925f1edcc1f20ae9cc4a44fffe487c9fa69" }
trussed = { git = "https://github.com/Nitrokey/trussed", rev = "6b9a43fbaaf34fe8d69fac0021f8130dd9a436c9" }
iso7816 = { git = "https://github.com/sosthene-nitrokey/iso7816.git", rev = "160ca3bbd8e21ec4e4ee1e0748e1eaa53a45c97f"}
se05x = { git = "https://github.com/Nitrokey/se05x.git", rev = "25f415fe49b8595b1321414f61da20e4f4f11510"} 
trussed-se050-backend = { git = "https://github.com/Nitrokey/trussed-se050-backend.git", rev = "2d34376a8451653cee9cd843ba9f09746e6d084b"} 
